owner: TrainyApp
repo: status

sites:
  - name: Trainy Website
    url: https://trainy.app
  - name: Trainy Backend (RBC)
    url: https://rbc.trainy.app/healthz
  - name: Untitled2 (Realtime data in Germany)
    url: https://untitled2.trainy.app/healthz
  - name: Germany Station Search
    url: https://de-stations.trainy.app/healhtz
    expectedStatusCodes: [404]
  - name: S-Bahn Munich Positions
    url: https://sbm-positions.trainy.app/healthz
  - name: Vehicle status MQTT Server (Trains in Germany and city transport in Hamburg and Munich)
    url: https://emqx-prod-nlb-ext.trainy.app/mqtt
    expectedStatusCodes: [400]

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.trainy.app
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/194303148?v=4
  name: Trainy Status
  introTitle: Trainy Status
  introMessage: Trainy is a tracker for your public transport journies
  navbar:
    - title: Trainy
      href: https://trainy.app
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TrainyApp

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
